import {
  BookOpen, Box, Briefcase, Bug, Calendar, CalendarDays, ClipboardList, Code2, Database, FileText, Flag,
  Folder, FolderKanban, Globe, GraduationCap, Heart, Layers, Library, Lightbulb, ListTodo, Map, MessageSquare,
  Notebook, Rocket, Shield, Sparkles, Star, Target, Users, Zap, Blocks, LayoutTemplate, Mail, Server, Cloud,
  Terminal, Ticket, BarChart3, Video, Link2, Wrench, Newspaper, Home, KanbanSquare, AppWindow, type LucideIcon,
} from "lucide-react";

/** Page icons users can pick; stored by name in the database. */
export const PAGE_ICONS: Record<string, LucideIcon> = {
  "file-text": FileText,
  notebook: Notebook,
  folder: Folder,
  "folder-kanban": FolderKanban,
  briefcase: Briefcase,
  blocks: Blocks,
  users: Users,
  "book-open": BookOpen,
  library: Library,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "list-todo": ListTodo,
  "clipboard-list": ClipboardList,
  "message-square": MessageSquare,
  lightbulb: Lightbulb,
  target: Target,
  flag: Flag,
  rocket: Rocket,
  sparkles: Sparkles,
  star: Star,
  bug: Bug,
  code: Code2,
  database: Database,
  globe: Globe,
  layers: Layers,
  box: Box,
  map: Map,
  shield: Shield,
  zap: Zap,
  heart: Heart,
  "graduation-cap": GraduationCap,
  "layout-template": LayoutTemplate,
  link: Link2,
  mail: Mail,
  server: Server,
  cloud: Cloud,
  terminal: Terminal,
  "app-window": AppWindow,
  ticket: Ticket,
  chart: BarChart3,
  video: Video,
  wrench: Wrench,
  newspaper: Newspaper,
  home: Home,
  kanban: KanbanSquare,
};

/** German names of the page icons (menus, tooltips, screen readers). */
export const PAGE_ICON_LABELS: Record<string, string> = {
  "file-text": "Dokument",
  notebook: "Notizbuch",
  folder: "Ordner",
  "folder-kanban": "Projektordner",
  briefcase: "Aktentasche",
  blocks: "Bausteine",
  users: "Personen",
  "book-open": "Buch",
  library: "Bibliothek",
  calendar: "Kalender",
  "calendar-days": "Kalendertage",
  "list-todo": "Aufgabenliste",
  "clipboard-list": "Checkliste",
  "message-square": "Nachricht",
  lightbulb: "Idee",
  target: "Ziel",
  flag: "Flagge",
  rocket: "Rakete",
  sparkles: "Funken",
  star: "Stern",
  bug: "Fehler",
  code: "Code",
  database: "Datenbank",
  globe: "Globus",
  layers: "Ebenen",
  box: "Paket",
  map: "Karte",
  shield: "Schild",
  zap: "Blitz",
  heart: "Herz",
  "graduation-cap": "Abschluss",
  "layout-template": "Vorlage",
  link: "Link",
  mail: "E-Mail",
  server: "Server",
  cloud: "Cloud",
  terminal: "Terminal",
  "app-window": "Programm",
  ticket: "Ticket",
  chart: "Diagramm",
  video: "Video",
  wrench: "Werkzeug",
  newspaper: "Zeitung",
  home: "Startseite",
  kanban: "Kanban",
};

/** The German name of a page icon (the stored name for unknown icons). */
export const iconLabel = (name: string) => PAGE_ICON_LABELS[name] ?? name.replace(/-/g, " ");

export function PageIcon({ name, size = 16, className }: { name: string | null | undefined; size?: number; className?: string }) {
  const Icon = (name && PAGE_ICONS[name]) || FileText;
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden />;
}
