import {
  BookOpen, Box, Briefcase, Bug, Calendar, CalendarDays, ClipboardList, Code2, Database, FileText, Flag,
  Folder, FolderKanban, Globe, GraduationCap, Heart, Layers, Library, Lightbulb, ListTodo, Map, MessageSquare,
  Notebook, Rocket, Shield, Sparkles, Star, Target, Users, Zap, Blocks, LayoutTemplate, Mail, Server, Cloud,
  Terminal, Ticket, BarChart3, Video, Mic, Link2, Wrench, Newspaper, Home, KanbanSquare, AppWindow, type LucideIcon,
} from "lucide-react";
import { t, type TKey } from "../lib/i18n";

/** Page icons users can pick; stored by name in the database. */
export const PAGE_ICONS: Record<string, LucideIcon> = {
  "file-text": FileText,
  notebook: Notebook,
  folder: Folder,
  "folder-kanban": FolderKanban,
  briefcase: Briefcase,
  blocks: Blocks,
  users: Users,
  "book-open": BookOpen,
  library: Library,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "list-todo": ListTodo,
  "clipboard-list": ClipboardList,
  "message-square": MessageSquare,
  lightbulb: Lightbulb,
  target: Target,
  flag: Flag,
  rocket: Rocket,
  sparkles: Sparkles,
  star: Star,
  bug: Bug,
  code: Code2,
  database: Database,
  globe: Globe,
  layers: Layers,
  box: Box,
  map: Map,
  shield: Shield,
  zap: Zap,
  heart: Heart,
  "graduation-cap": GraduationCap,
  "layout-template": LayoutTemplate,
  link: Link2,
  mail: Mail,
  mic: Mic,
  server: Server,
  cloud: Cloud,
  terminal: Terminal,
  "app-window": AppWindow,
  ticket: Ticket,
  chart: BarChart3,
  video: Video,
  wrench: Wrench,
  newspaper: Newspaper,
  home: Home,
  kanban: KanbanSquare,
};

/** Catalog keys of the page icon names (menus, tooltips, screen readers). */
const PAGE_ICON_LABELS: Record<string, TKey> = {
  "file-text": "icon.fileText",
  notebook: "icon.notebook",
  folder: "icon.folder",
  "folder-kanban": "icon.folderKanban",
  briefcase: "icon.briefcase",
  blocks: "icon.blocks",
  users: "icon.users",
  "book-open": "icon.bookOpen",
  library: "icon.library",
  calendar: "icon.calendar",
  "calendar-days": "icon.calendarDays",
  "list-todo": "icon.listTodo",
  "clipboard-list": "icon.clipboardList",
  "message-square": "icon.messageSquare",
  lightbulb: "icon.lightbulb",
  target: "icon.target",
  flag: "icon.flag",
  rocket: "icon.rocket",
  sparkles: "icon.sparkles",
  star: "icon.star",
  bug: "icon.bug",
  code: "icon.code",
  database: "icon.database",
  globe: "icon.globe",
  layers: "icon.layers",
  box: "icon.box",
  map: "icon.map",
  shield: "icon.shield",
  zap: "icon.zap",
  heart: "icon.heart",
  "graduation-cap": "icon.graduationCap",
  "layout-template": "icon.layoutTemplate",
  link: "icon.link",
  mail: "icon.mail",
  mic: "icon.mic",
  server: "icon.server",
  cloud: "icon.cloud",
  terminal: "icon.terminal",
  "app-window": "icon.appWindow",
  ticket: "icon.ticket",
  chart: "icon.chart",
  video: "icon.video",
  wrench: "icon.wrench",
  newspaper: "icon.newspaper",
  home: "icon.home",
  kanban: "icon.kanban",
};

/** The name of a page icon in the display language (the stored name for unknown icons). */
export const iconLabel = (name: string) => (PAGE_ICON_LABELS[name] ? t(PAGE_ICON_LABELS[name]) : name.replace(/-/g, " "));

export function PageIcon({ name, size = 16, className }: { name: string | null | undefined; size?: number; className?: string }) {
  const Icon = (name && PAGE_ICONS[name]) || FileText;
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden />;
}
